### ISSUE TITLE
Server crashed from an unhandled promise

### ISSUE THREAD

**Issue by kwunyeung** [forbole/big-dipper-celo-server#16]
```
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.825(0)? (STDERR) (node:248114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11160)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.825(0)? (STDERR) (node:248114) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.826(0)? (STDERR)     at Object.InvalidResponse (/home/forbole/bd-celo-server/node_modules/web3-core-helpers/src/errors.js:42:16)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.826(0)? (STDERR)     at XMLHttpRequest.request.onreadystatechange (/home/forbole/bd-celo-server/node_modules/web3-providers-http/src/index.js:98:32)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.826(0)? (STDERR)     at XMLHttpRequestEventTarget.dispatchEvent (/home/forbole/bd-celo-server/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.826(0)? (STDERR)     at XMLHttpRequest._setReadyState (/home/forbole/bd-celo-server/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.826(0)? (STDERR)     at XMLHttpRequest._onHttpRequestError (/home/forbole/bd-celo-server/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.826(0)? (STDERR)     at ClientRequest.<anonymous> (/home/forbole/bd-celo-server/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.826(0)? (STDERR)     at ClientRequest.emit (events.js:311:20)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.833(0)? (STDERR)     at ClientRequest.EventEmitter.emit (domain.js:482:12)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.833(0)? (STDERR)     at TLSSocket.socketErrorListener (_http_client.js:426:9)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.833(0)? (STDERR)     at TLSSocket.emit (events.js:311:20)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.833(0)? (STDERR)     at TLSSocket.EventEmitter.emit (domain.js:482:12)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.833(0)? (STDERR)     at emitErrorNT (internal/streams/destroy.js:92:8)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.833(0)? (STDERR)     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.834(0)? (STDERR)     at processTicksAndRejections (internal/process/task_queues.js:84:21)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.834(0)? (STDERR) (node:248114) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11161)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.834(0)? (STDERR) (node:248114) UnhandledPromiseRejectionWarning: Error: Invalid JSON RPC response: ""
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.834(0)? (STDERR)     at Object.InvalidResponse (/home/forbole/bd-celo-server/node_modules/web3-core-helpers/src/errors.js:42:16)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.834(0)? (STDERR)     at XMLHttpRequest.request.onreadystatechange (/home/forbole/bd-celo-server/node_modules/web3-providers-http/src/index.js:98:32)
Jul 28 21:19:32 bd-celo start-bd.sh[215081]: W20200728-21:19:32.834(0)? (STDERR)     at XMLHttpRequestEventTarget.dispatchEvent (/home/forbole/bd-celo-server/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.127(0)? Error: Invalid JSON RPC response: ""
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.128(0)?     at Object.InvalidResponse (/home/forbole/bd-celo-server/node_modules/web3-core-helpers/src/errors.js:42:16)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.128(0)?     at XMLHttpRequest.request.onreadystatechange (/home/forbole/bd-celo-server/node_modules/web3-providers-http/src/index.js:98:32)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.128(0)?     at XMLHttpRequestEventTarget.dispatchEvent (/home/forbole/bd-celo-server/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.128(0)?     at XMLHttpRequest._setReadyState (/home/forbole/bd-celo-server/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.128(0)?     at XMLHttpRequest._onHttpRequestError (/home/forbole/bd-celo-server/node_modules/xhr2-cookies/dist/xml-http-request.js:349:14)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.128(0)?     at ClientRequest.<anonymous> (/home/forbole/bd-celo-server/node_modules/xhr2-cookies/dist/xml-http-request.js:252:61)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.128(0)?     at ClientRequest.emit (events.js:311:20)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.129(0)?     at ClientRequest.EventEmitter.emit (domain.js:482:12)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.129(0)?     at TLSSocket.socketErrorListener (_http_client.js:426:9)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.129(0)?     at TLSSocket.emit (events.js:311:20)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.129(0)?     at TLSSocket.EventEmitter.emit (domain.js:482:12)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.129(0)?     at emitErrorNT (internal/streams/destroy.js:92:8)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.129(0)?     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.129(0)?     at processTicksAndRejections (internal/process/task_queues.js:84:21)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.129(0)?  => awaited here:
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.129(0)?     at Function.Promise.await (/home/forbole/.meteor/packages/promise/.0.11.2.iatt1i.xuutn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.130(0)?     at imports/api/validators/server/methods.ts:14:22
Jul 28 21:20:28 bd-celo start-bd.sh[215081]: I20200728-21:20:28.130(0)?     at /home/forbole/.meteor/packages/promise/.0.11.2.iatt1i.xuutn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by kwunyeung** [comment]
should have been fixed
